### ISSUE TITLE
arrows on edges

### ISSUE THREAD

**Issue by bzd2000** [dash14/v-network-graph#1]
Hi,

Very nice library!
I just wonder if it is possible to have arrows on the edges to indicate the flow?

kr,
Filip.

**Comment by dash14** [comment]
Thanks for your feedback.
The arrows on the edges are exactly the feature I'm working on right now!
Here's a screenshot in development.

![arrows](https://user-images.githubusercontent.com/24878247/130703359-71383006-d7ac-431f-bbaa-e6f7b09783b5.png)

It's a bit large modification, so it will take a few more days to release.

Best regards,
dash14.

**Comment by bzd2000** [comment]
Hi @dash14 ,

Thx for the update!
Again ... really nice and will written library.

**Comment by dash14** [comment]
Hi @bzd2000,

Thank you very much for your positive feedback!
This motivates me a lot.
