### ISSUE TITLE
Use Custom Node 

### ISSUE THREAD

**Issue by Ulrich15** [dash14/v-network-graph#106]
Hi Thanks you for this Awesome librairie.

I want to know if it's possible to have a custom node (with Div and HTML markup) like this image 

![image](https://user-images.githubusercontent.com/60409730/225284506-fbb7c28e-62fe-4917-8125-7ab92e367f9c.png)

Because i see the fact all things are render in svg limit the posibility to custom node as we want.

Thanks you 🙏

**Comment by dash14** [comment]
I close this issue for now.
If you have any other question/comment, please reopen this issue.
