### ISSUE TITLE
Set d3-force as a peer dependency

### ISSUE THREAD

**Issue by vonWolfehaus** [dash14/v-network-graph#108]
Great library, thank you! Now, rather than including d3-force for all projects, it would be nice to keep it out of the bundle so that apps like mine do not have the extra payload for something we don't use. Every kb counts! Thanks again.

**Comment by dash14** [comment]
Hi @vonWolfehaus,
Thank you for your feedback!
Please be informed that a new version ([v0.9.1](https://github.com/dash14/v-network-graph/releases/tag/v0.9.1)) has been released with d3-force changed to an optional dependency.

**Comment by vonWolfehaus** [comment]
Thank you very much!
