### ISSUE TITLE
Convert vNG from plugin to component

### ISSUE THREAD

**Issue by vonWolfehaus** [dash14/v-network-graph#109]
In order to support tree-shaking such that the component is loaded only when needed (rather than bundled with the main app), vNG will need to become a pure component that can simply be imported within another vue component. Otherwise it is a feature that will bloat an app for users who do not use vNG (ie users of the app that vNG is being used in). I hope that makes sense...

This is a wonderful component and I hope you are able to accommodate this request. I'm still working on it but it might be the graph that I can use in my app. Thank you very much! It is extremely well-designed!

**Comment by dash14** [comment]
Thank you for your feedback!
Originally, v-network-graph did not require registration as a plugin and could be imported from other components.
I have added an example of its usage to the document.
https://dash14.github.io/v-network-graph/getting-started.html#installation
