### ISSUE TITLE
Does this library supports to javascript?

### ISSUE THREAD

**Issue by PavankalyanPayyavula** [dash14/v-network-graph#111]

**Comment by dash14** [comment]
Hi @PavankalyanPayyavula,
Sorry for the late reply.

> Does this library supports to javascript?

Yes, the v-network-graph library does not require TypeScript and will work with JavaScript.
Please see https://github.com/dash14/v-network-graph/issues/27

**Comment by PavankalyanPayyavula** [comment]
Hi @dash14,

Thank you for the response, it helps a lot.
