### ISSUE TITLE
Is it possible to add images when we use position nodes with d3 force?

### ISSUE THREAD

**Issue by PavankalyanPayyavula** [dash14/v-network-graph#114]
I am using v-network-graph with javascript, 
Is it possible to add images when we use position nodes with a d3 force?
I am using Webpack5 and Vue3 and node version 12.18.0

**Comment by dash14** [comment]
Hi @PavankalyanPayyavula,
Yes, I think it is possible to combine the display of images and positioning by d3-force.
And, although each example is in TypeScript, it is also possible to write it in JavaScript without writing the type.

Examples:
https://dash14.github.io/v-network-graph/examples/appearance.html#custom-node
https://dash14.github.io/v-network-graph/examples/layout.html#position-nodes-with-d3-force

Please ask again if there are any further specifics that are unclear or do not work hereafter.

**Comment by dash14** [comment]
I close this issue for now.
If you have any question/comment, please reopen this issue.
