### ISSUE TITLE
Auto pan and zoom w/dynamic insertion of nodes, edges and layout

### ISSUE THREAD

**Issue by notsonsi** [dash14/v-network-graph#119]
I was wondering if this is a thing or not or how I could fix this, I insert my nodes, edges and layout from a database so all dynamically and I have autoPanAndZoomOnLoad: "fit-content", which doesn't work since it runs before the nodes, edges and layout are added from the database, also if the database changes and it updates the autoPanAndZoomOnLoad wont do, is there any other way to do this? thanks ^^

**Comment by dash14** [comment]
@notsonsi
In [v0.9.4](https://github.com/dash14/v-network-graph/releases/tag/v0.9.4), we added the ability to wait for asynchronous processing before initial display!
After the asynchronous processing is completed, the `autoPanAndZoomOnLoad` config will be applied.
See the example for details.
https://dash14.github.io/v-network-graph/examples/basic.html#processing-before-initial-display

Thank you for your patience!

**Comment by dash14** [comment]
I close this issue for now.
If you have any other question/comment, please reopen this issue.
