### ISSUE TITLE
Any advice for physic rendering?

### ISSUE THREAD

**Issue by kogratte** [dash14/v-network-graph#128]
Hello!

This is not an issue nor a request, moreover a request for advice.

I was using until now a lib named vis-network, which was working pretty well but was hard to manage, and nearly impossible to customize.

This latest reason is the one who make me switch to v-network-graph. Anyway, I'm used to the barnesHut physic model, which is... way more efficient than the one you provides as example in documentation.

From what I understand, this is not an issue tied to this lib itself, as you rely on third party implementations. What I would like to know, is which kind of graph libs you may have seen with v-network-graph, and which one offer the best results.

What I want to achieve is a dynamic map (interactive), where the user is able to add links (aka edges) between nodes in order to design a network topology.

You'll find examples in attachement.

From what I see for the time being, the provided example is very bad and results are ugly. There is no mass vector nor any repulsion attributes, which makes things very difficult to customize.
<img width="1393" alt="Screenshot 2023-09-05 at 16 46 01" src="https://github.com/dash14/v-network-graph/assets/1905621/b20014d8-9a22-4682-894a-c43b55c4dc55">
<img width="1389" alt="Screenshot 2023-09-05 at 16 46 14" src="https://github.com/dash14/v-network-graph/assets/1905621/60b1c8d7-d471-4688-a0c5-6090583fd985">

**Comment by dash14** [comment]
Hi @kogratte,
Thank you for using v-network-graph library!

> What I would like to know, is which kind of graph libs you may have seen with v-network-graph, and which one offer the best results.

Unfortunately, I have not seen many v-network-graphs used in combination with other graph libs, so I cannot give an adequate answer.
Sorry I can't help you....

**Comment by kogratte** [comment]
Fair enough :) Then I'll need to do it by myself.
FTR, the goal is to use https://github.com/visjs/vis-network/blob/master/lib/network/modules/PhysicsEngine.js.

**Comment by zamplyy** [comment]
I have a similar use case, would be great if you could share your discoveries 👍  @kogratte

**Comment by kogratte** [comment]
For the record, I've not been able to deep dive into the implementation, both cause of ROI, available time and motivation (once faced the amount of work it represents). I stick to what is available, including drawbacks.
