### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by zamplyy** [dash14/v-network-graph#130]
I found while trying out the library that we always render the VEdgeOverlay even though i didn't use the slots. 
For performance reasons i think we should only render the edge overlays when we use the slot.

I made a PR to fix this [#129](https://github.com/dash14/v-network-graph/pull/129)

**Comment by dash14** [comment]
Hi @zamplyy,
Thank you so much!!
As you pointed out, it was rendered even when it was not needed.
Merged the PR from you and released [v0.9.8](https://github.com/dash14/v-network-graph/releases/tag/v0.9.8)!

**Comment by zamplyy** [comment]
No problem! Thanks for merging so quickly 👍
