### ISSUE TITLE
Error with curved edges & force layout

### ISSUE THREAD

**Issue by hpawa** [dash14/v-network-graph#133]
When using ForceLayout and edge type curved error in the console
`Error: Problem parsing d="M 0 0 Q NaN NaN NaN NaN Q NaN NaN NaN NaN Q NaN NaN NaN NaN Q NaN NaN 0 0"`
[Reproduction](https://stackblitz.com/edit/vitejs-vite-xtpvnu)

**Comment by dash14** [comment]
Thank you for your contribution!
Merged #134 and released the fix as [v0.9.10](https://github.com/dash14/v-network-graph/releases/tag/v0.9.10)!
