### ISSUE TITLE
Failed to resolve import "v-network-graph/lib/layouts/force" Does the file exist?

### ISSUE THREAD

**Issue by Koffer0-0** [dash14/v-network-graph#141]
Hey, have issue with the importng ForceLayout, even installing and uninstaling d3-force, didn't help. I saw that installing the lib not required. The reason that, I can navigate to this file, but vite plugin gives error.

import {ForceLayout} from "v-network-graph/lib/layouts/force";
![image](https://github.com/dash14/v-network-graph/assets/68071028/c8d4b114-5f5b-49ee-abd1-95a0c167ec3a)

**Comment by dash14** [comment]
Hi @Koffer0-0,
Please try the following code!

```ts
import { ForceLayout } from "v-network-graph/lib/force-layout"
```

**Comment by Koffer0-0** [comment]
Thanks! it works!
