### ISSUE TITLE
Add touch events for mobile

### ISSUE THREAD

**Issue by vonWolfehaus** [dash14/v-network-graph#144]
I'm using v-network-graph on my website that needs to be mobile-ready. I can pan and select nodes, but cannot move them around.

Is there a plan to add this for mobile support?

**Comment by dash14** [comment]
Hi @vonWolfehaus,
I am very sorry that I have not been able to reply to you.
The following sample website can be opened on a mobile device to move the node.
https://dash14.github.io/v-network-graph/
If you still can't get it to work on this site, can you tell us the OS and version of the mobile device you have checked?

**Comment by vonWolfehaus** [comment]
My turn to be sorry, it's been busy. The docs site does work on mobile, so I'm not sure why it isn't working on my end. I'll have to dig a bit. Closing this.
