### ISSUE TITLE
Node width

### ISSUE THREAD

**Issue by EvgenyFrol** [dash14/v-network-graph#147]
Hi!

How can I set the automatic width of a node based on the filling of the label inside the node?
I haven't found an example with a similar case, but in docs said that the width of a node has only some definitely static value

![image](https://github.com/dash14/v-network-graph/assets/56683425/18b05b9b-c93e-4252-8d3b-18e1005375b4)

Сan you advise me how to solve this problem?

**Comment by dash14** [comment]
I close this issue for now.
If you have any other question/comment, please reopen this issue.
