### ISSUE TITLE
Is it possible to set different width for edges or paths between nodes?

### ISSUE THREAD

**Issue by r3code** [dash14/v-network-graph#148]
Is it possible to draw a graph with different width edges? 
Here the picture 
![image](https://github.com/dash14/v-network-graph/assets/1355056/3063ea3e-3246-4861-a733-8de4510cab6f)

**Comment by dash14** [comment]
Hi @r3code,
Sorry I have not been able to respond to you for a long time.
Yes, it is possible.
Please take a look at the example below, which also shows how to specify different width settings for each edge.
https://dash14.github.io/v-network-graph/examples/appearance.html#change-the-appearance-of-each-node-and-edge

**Comment by dash14** [comment]
I close this issue for now.
If you have any other question/comment, please reopen this issue.
