### ISSUE TITLE
fix get started guide

### ISSUE THREAD

**Issue by N1neTa1ls** [dash14/v-network-graph#15]
https://dash14.github.io/v-network-graph/getting-started.html
it says what needs to be added to main.js here it is
<img width="867" alt="browser_jsCiNDod4v" src="https://user-images.githubusercontent.com/73495645/142013321-ec7ef53f-6a68-4dec-8bd8-df5714670fbf.png">
But this construction using in Vue 2
In Vue 3 need using this construction
```
import { createApp } from 'vue'
import App from './App.vue'
import VNetworkGraph from "v-network-graph"
import "v-network-graph/lib/style.css"

createApp(App).use(VNetworkGraph).mount('#app')  
```

it's my first time using Vue 3 and I didn't immediately understand why nothing works for me and what to do with it))
please fix this error and it would be great to sign the names of the files in which you want to make these imports (main.js) I think junior developers will appreciate it)

P.s. if an entry in main.js was used as in vue 2, does this mean that v-network-graph will work in vue 2 as well?

**Comment by dash14** [comment]
Thank you for pointing this out.
I have just fixed the description to the correct procedure.
I'm sorry for the inconvenience.
(And, unfortunately, v-network-graph does not work with Vue2.)
