### ISSUE TITLE
Multiline label texts are incorrectly positioned in Safari

### ISSUE THREAD

**Issue by ctrueblood-epri** [dash14/v-network-graph#16]
### Problem

When using Safari browser on iPhone or Mac computer, if a text label is multiple lines (i.e., contains `\n`) then the entire label is shifted upwards when rendered on the graph (assuming label direction = south).

### Likely Cause

https://github.com/dash14/v-network-graph/blob/4e91d30d6912a56697de8f693c4f3042c881d372/src/components/label-text.vue#L156-L161

When a `<tspan>` is rendered in Safari, it does not seem to inherit the `dominant-baseline` attribute from the parent `<text>` element. Chrome, Firefox, and Edge do not seem to have this issue.

### Proposed Solution

Consider setting `dominant-baseline` directly on `<tspan>` in addition to `<text>`.

> Reference: https://stackoverflow.com/a/42023579  
> "Apparently, Safari wants the inner tspan have the dominant baseline set..."

**Comment by dash14** [comment]
Hi @ctrueblood-epri,
Thank you very much for your report.
I have implemented the solution you suggested.
Please check it out [v0.3.7](https://github.com/dash14/v-network-graph/releases/tag/v0.3.7).
