### ISSUE TITLE
Disable scale for grid when scalingObjects: true

### ISSUE THREAD

**Issue by justfry** [dash14/v-network-graph#17]
I have following config
```
view: {
        panEnabled: true,
        zoomEnabled: true,
        scalingObjects: true,
        fit: true,
        layoutHandler: new GridLayout({ grid: 20 }),
        grid: {
            visible: true,
        },
    },
 ```
 
 And `<g class="v-background-viewport"...` scaling along with other objects with grid on background
 
![image](https://user-images.githubusercontent.com/35431809/142600002-de1e6afa-05e1-4e88-8861-782f42bc921b.png)

When i turn scalingObjects option to false everything back to normal, but my task is scale nodes and edges on zoom and leave background grid fullscreen.
![image](https://user-images.githubusercontent.com/35431809/142600168-75e82c09-8381-45ac-a718-9a1885044dab.png)

**Comment by dash14** [comment]
Hi @justfry,
Thank you very much for your report.
Fixed grid scaling when `scalingObjects: true` is specified.
Please check it out [v0.3.7](https://github.com/dash14/v-network-graph/releases/tag/v0.3.7).

**Comment by justfry** [comment]
@dash14 Oh my god it works! Thank you!
