### ISSUE TITLE
tooltip

### ISSUE THREAD

**Issue by MohandesaliRahnema** [dash14/v-network-graph#19]
how can i show node info via tootip on hover on node

**Comment by dash14** [comment]
Hi @MohandesaliRahnema,

Thank you for your question.
v-network-graph does not have the ability to display Tooltips. However, it is possible to realize Tooltip by using the features of events and coordinate translation.

I have created a new example. Please see below:
https://dash14.github.io/v-network-graph/examples/event.html#tooltip
Please note that the latest version ([v0.3.8](https://github.com/dash14/v-network-graph/releases/tag/v0.3.8)) is required to use the coordinate translation feature.

**Comment by dash14** [comment]
I'll close this issue for now.
If you have any other questions, please open a new issue.

**Comment by MohandesaliRahnema** [comment]
thank you a lot
it is very useful future
