### ISSUE TITLE
Sponsoring the great work (Github Sponsors or buymeacoffee or any other way)

### ISSUE THREAD

**Issue by markus-ebner** [dash14/v-network-graph#23]
Hi @dash14,

is there any way to sponsor your work for this amazing library? 

Something like github sponsor, buy me a coffee, etc.

Best regards

**Comment by dash14** [comment]
Hi @markus-ebner,

Wow, thanks for the very nice suggestion.
I hadn't idea about being sponsored, but since you suggested it, I created a buymeacoffee account to try it out.
Please see the bottom of the README.md.

Best Regards

**Comment by markus-ebner** [comment]
Uh nice, I am using your library very much in the last months, and it really helped me to build something cool 👍

**Comment by dash14** [comment]
Thank you so so so much!!
I'm glad that I can help you.
Please continue to send me your feedback and suggestions.
