### ISSUE TITLE
node image prevent to show node stroke

### ISSUE THREAD

**Issue by MohandesaliRahnema** [dash14/v-network-graph#25]
hii use image as node and then when i want to use  storke  for the same node it will be hide behind the image
how can i fix this issue

**Comment by MohandesaliRahnema** [comment]
hi i use image as node and then when i want to use stroke for the same node it will be hide behind the image
how can i fix this issue

**Comment by dash14** [comment]
Hi @MohandesaliRahnema,
I think it is possible to do this by inserting the circle that draws the node stroke after the image.
I changed the node image example to do so. I hope this is helpful.
https://dash14.github.io/v-network-graph/examples/appearance.html#custom-node

**Comment by MohandesaliRahnema** [comment]
thank you a lot you save my day
excuse me i have two another question
1- how can i have two image on a node for ex. i want to show os icon as a
small circle on right bottom of a node where the node has an image itself
for ex a node have status image via sub img to show os
2- the event that return on node click has no attr offsetx and offset on
event.target
best regards

**Comment by dash14** [comment]
> 1- how can i have two image on a node

As implemented in the example, the image is just an SVG `<image>` tag.
You can put as many as you want between `<template #override-node="..."> ~ </template>`.
The display position of the placed element can be adjusted with x and y. The coordinates of the center of the node are `(0,0)`.

> 2- the event that return on node click has no attr offsetx and offset on event.target

There are no offset attributes in SVG Element, so try using getBoundingClientRect() or getBBox().

**Comment by MohandesaliRahnema** [comment]
thank you very much

**Comment by MohandesaliRahnema** [comment]
[image: image.png]
when i use two template for image i got above error

**Comment by dash14** [comment]
I can't see the image... I don't know how you are writing the code, so I'll guess.
Are you writing two `<template template #override-node>`?
This `<template>` is to replace a node, and can only be written once.
I think you want to use multiple tags (elements) to represent a node.
So please put two `<image>` inside one `<template #override-node>`.

**Comment by MohandesaliRahnema** [comment]
oh yahhhh...
thank you very much

**Comment by dash14** [comment]
Thanks for your reply.
I'll close this issue for now.
If you have any other questions, please open a new issue.
