### ISSUE TITLE
Nuxt 3 support

### ISSUE THREAD

**Issue by avxkim** [dash14/v-network-graph#34]
Hi, do you plan to support Nuxt 3?

**Comment by dash14** [comment]
Hi @avxkim,
Sorry for the late reply.
Fixed some problems for use with Nuxt 3. And, I added installation instructions in [README](https://github.com/dash14/v-network-graph#readme) and [Getting Started](https://dash14.github.io/v-network-graph/getting-started.html#installation-on-nuxt-3-project).
