### ISSUE TITLE
Feature request: Events for double click

### ISSUE THREAD

**Issue by dashavoo** [dash14/v-network-graph#37]
There are events for view, node, edge and path clicks. It would be useful to have a separate event for double-click.
I have tried to handle this in the event handler, but my solutions were a bit complex. It would probably be simpler to handle at the library level.

**Comment by dash14** [comment]
Hi @dashavoo,

Thank you for your feedback.
As you mentioned, it would be nice if the double-click event could be handled by the library.
So, I just released a new version([v0.4.0](https://github.com/dash14/v-network-graph/releases/tag/v0.4.0)) that adds a "dblclick" event to each element that has a "click" event.
Please refer to [release page](https://github.com/dash14/v-network-graph/releases/tag/v0.4.0) for details.

Best Regards,

**Comment by dashavoo** [comment]
Thank you!!
