### ISSUE TITLE
It is not possible to pan (focus on a specific node) on load

### ISSUE THREAD

**Issue by pavelhoral** [dash14/v-network-graph#41]
I am trying to focus on a specific node when the graph gets loaded. However it seems that there is always a call to `panToCenter` after `view:loaded` event is fired.

This behavior can be observed on the examples page - https://dash14.github.io/v-network-graph/examples/event.html#capture-all-events:

![obrazek](https://user-images.githubusercontent.com/2012726/156884301-f33186c0-c55b-48f6-9458-93020a442c2c.png)

This behavior forces users to pan in `setTimeout` (so there is a workaround).

**Comment by pavelhoral** [comment]
Also first mouswheel zoom seems to be broken and tries to initialize itself to "fit graph". But that is probably unrelated bug.

**Comment by dash14** [comment]
Hi @pavelhoral,
Thank you for your report.
Centering on load was implemented intentionally, but I did not provide a way to disable it.
I have just added this feature and released it. ([v0.5.1](https://github.com/dash14/v-network-graph/releases/tag/v0.5.1))
Also created an [example](https://dash14.github.io/v-network-graph/examples/misc.html#centering-on-load), please check it out.

By the way, I have not been able to reproduce the mouse wheel zoom problem. If this problem still occurs after this fix, more detailed information would be appreciated. (e.g., browser you use, minimum reproduction code, etc.)

**Comment by pavelhoral** [comment]
Thank you, awesome work! If I came across the zoom issue again I will create a separate issue here on github.
