### ISSUE TITLE
Tapping on node on mobile does not select it

### ISSUE THREAD

**Issue by violent-boomerang** [dash14/v-network-graph#42]
Hello,
I wanted to know, with node selection enabled,  why on mobile/tablet "tapping" a node does not select the node itself.

Using the [capture all exampe](https://dash14.github.io/v-network-graph/examples/event.html#capture-all-events) I can see that clicked and selected are not fired, but pointerdown, pointerup and many other node events are fired, and generally mobile seems to be well supported

Many thanks

**Comment by dash14** [comment]
Hi @violent-boomerang,

Thank you very much for reporting! This was a bug....
It seems to have been contaminated when the event processing was revised to support `dblclick` in the past.
Now recognizes click operations in mobile browsers, even with multi-touch. Please check it out. ([v0.5.3](https://github.com/dash14/v-network-graph/releases/tag/v0.5.3))

Kind Regards,

**Comment by violent-boomerang** [comment]
I am afraid some regression has been introduced with the fix, the [coordinates translation example](https://dash14.github.io/v-network-graph/examples/misc.html#coordinates-translation), that worked in previous rev, now is not working.
