### ISSUE TITLE
regression in 0.5.3

### ISSUE THREAD

**Issue by violent-boomerang** [dash14/v-network-graph#43]
Hello, i noticed that [coordinates translation example](https://dash14.github.io/v-network-graph/examples/misc.html#coordinates-translation), that worked in rev previous to 0.5.3, now is not working.

**Comment by dash14** [comment]
Hi @violent-boomerang,
Thank you very much for your report!!
Fix the `event.offsetX/Y` values were not calculated correctly. ([v0.5.4](https://github.com/dash14/v-network-graph/releases/tag/v0.5.4))

Kind Regards,

**Comment by violent-boomerang** [comment]
Great! fixed, though it seems now there is another issue:
Double click/tap on mobile on node or edge is not working, it is on view though. I am not 100% percent sure if it was working before 0.5.3
Many thank for your work

**Comment by violent-boomerang** [comment]
No, just checked it did not work in 0.5.2, this is then not related, I'll open a dedicated issue and close this one
