### ISSUE TITLE
node and edge :dblclick not fired on mobile

### ISSUE THREAD

**Issue by violent-boomerang** [dash14/v-network-graph#44]
Hello, here some issues I have found while testing rev 0.5.3

- node:dblclick and edge:dblclick are not fired on mobile, they work on desktop
- node:click is fired on mobile but "event.detail" value is always 1 on mobile.

view:dblclick is working OK on mobile and desktop

Thank you and Best Regards!

**Comment by dash14** [comment]
Hi @violent-boomerang,
Thank you for your report!
Sorry for the delay, I have fixed the bug and released it. ([v0.5.5](https://github.com/dash14/v-network-graph/releases/tag/v0.5.5))

Kind Regards,

**Comment by violent-boomerang** [comment]
Hello, checked on mobile, works!.
Thank you and best regards
