### ISSUE TITLE
long press event, suggested feature

### ISSUE THREAD

**Issue by violent-boomerang** [dash14/v-network-graph#45]
Hello, I am using your library on a tablet oriented project, so I rely on touch gestures.

I would like to use a context menu, but on mobile i cannot make a "right click".
On mobile often a right click is performed via long press so this would be a possible way for having that.
Is there already available something for a context menu on mobile that I am missing?

Thank you and best regards.

**Comment by dash14** [comment]
Hi @violent-boomerang,
When I was fixing #44, I did a slight update to the event processing. As a result, the `node:contextmenu`, `view:contextmenu` events are now fired by the long press operation.  This is made possible by the browser's default event handling. It seems that this was unintentionally suppressed until this update.
Does this behavior satisfy your requirements?

Best Regards,

**Comment by violent-boomerang** [comment]
Hello,
It satisfies my requirement, though I noticed using the Capture all events example that after node:context has fired also view:context is fired, is this the desired behaviour?
Many Thanks

**Comment by dash14** [comment]
Thank you for pointing this out! Sorry for repeating.
Fixed in [v0.5.7](https://github.com/dash14/v-network-graph/releases/tag/v0.5.7)

Best Regards,
