### ISSUE TITLE
Possibility to set a fixed centered node for force layout

### ISSUE THREAD

**Issue by markus-ebner** [dash14/v-network-graph#5]
I don't know if it is possible to fix a node to the center of the visualization in a force layout.
If so, it would be nice to add it to the documentation. 

If not, see it as a feature request ;) 

It would be super helpful, if someone could add this functionality to this amazing visualization package.

**Comment by dash14** [comment]
Hi @markus-ebner,

Thanks for asking.
I have written a simple example to fix the position of a node to the center of a field.
https://dash14.github.io/v-network-graph/examples/layout.html#fix-the-position-of-a-specific-node-in-the-force-layout

Does this example satisfy what you want to know?
What I bothered, a node placed in the center can be draggable by user.
Now, v-network-graph can specify whether all nodes are draggable or not, but it cannot specify whether a particular node is draggable or not. I plan to make this possible in the future.
Please let me know if you don't want users to be able to drag a fixed position node. I will try to implement this ahead of schedule.

If you have any other concerns, please let me know.

**Comment by markus-ebner** [comment]
Hi @dash14, thanks for the fast response and the provided example, it was very helpful. 

It would be great, that users are not able to drag a fixed node! Thanks for your amazing work @dash14!!
Pretty nice package. 

Besides that, I have two more questions/issues: 
- What do you think of victor as dev dependcies? It is pretty unmaintained (last update 6 years ago, some issues open, some PR open) - issue #6 
- Is it possible to have a different force configuration for different nodes/edges? - issue #7

**Comment by dash14** [comment]
Hi @markus-ebner,

Thanks for your reply and for closing the issue. I'm glad the example was helpful to you.
OK, I will try to implement a support to prevent dragging of specific node in the near future.

And, I'll reply to other issues there.
