### ISSUE TITLE
Markers' gaps is changing on move with large wide node

### ISSUE THREAD

**Issue by arik-levin** [dash14/v-network-graph#57]
Hi,

I created a component based on [arrow on edges](https://dash14.github.io/v-network-graph/examples/appearance.html#arrow-on-edges) example.

I changed one of the nodes to be with the following values [width: 150, type: "rect"]
When dragging the changed node, the markers get a large gap on some areas.

<img width="318" alt="Screen Shot 2022-05-12 at 11 12 35" src="https://user-images.githubusercontent.com/102540719/168025433-ca8081b0-c2c1-42ca-ad3f-77c75052b94f.png">

**Comment by dash14** [comment]
Hi @arik-levin,
Thank you for the bug report!
Incorrect calculations have been fixed and released. Please check [v0.5.15](https://github.com/dash14/v-network-graph/releases/tag/v0.5.15).

Kind Regards,

**Comment by arik-levin** [comment]
Hi,

Thank you for the quick response.

Cheers

**Comment by arik-levin** [comment]
Hi,

I verified the fix - looks great.
When will you publish the npm ?

**Comment by dash14** [comment]
Hi @arik-levin,
Sorry, I forgot!
I just published it now!!
