### ISSUE TITLE
victor as devDependency - not really maintained - action needed?

### ISSUE THREAD

**Issue by markus-ebner** [dash14/v-network-graph#6]
What do you think of victor as dev dependencies? 
It is pretty unmaintained (last update 6 years ago, some issues open, some PR open)

**Comment by dash14** [comment]
Thank you for your feedback.
It has been very helpful in speeding up the development process, but I actually had some trouble with unfixed bugs.
When the development progresses a little further, I would like to consider having vector calculation code inside, or changing to another library.
If you know of any good 2d vector library, please let me know.

**Comment by markus-ebner** [comment]
Thanks for the clarification. 
Unfortunately, I don't know any good 2d libraries.

**Comment by dash14** [comment]
It took some time, but I implemented the calculation process internally and removed victor as a dependency. ([v0.5.0](https://github.com/dash14/v-network-graph/releases/tag/v0.5.0))
Thank you for bringing up the issue!
