### ISSUE TITLE
SVG blocks page scrolling

### ISSUE THREAD

**Issue by bureauvanlieshout** [dash14/v-network-graph#65]
Thank you for the fantastic v-network-graph! I implemented it on a project. There is also information beneath the graph area. I disabled zoom etc., but when a user scrolls (mousewheel, trackpad etc.), nothing happens. The page does not scroll. 
THe "Disable mouse operations" example has the same effect. Mouse operations on the graph are diabled, but also on the page as a whole?
Do you have a solution for me, so that I can disable zoom and pan on the graph, but scroll the page while my pointer is over the graph?
Thank you, Bart

**Comment by dash14** [comment]
Hi @bureauvanlieshout,
Thank you for your feedback!
Regardless of the configs, mouse and touch events were being blocked, so the behavior has been changed.
To use the features described below, please update `v-network-graph` to [v0.5.19](https://github.com/dash14/v-network-graph/releases/tag/v0.5.19).

To allow mouse wheel scrolling on the page, please set `view.zoomEnabled` or `view.mouseWheelZoomEnabled` to `false`.

```ts
const configs = defineConfigs({
  view: {
    zoomEnabled: false,
  },
})
```

To allow scrolling by touch on the page as well, set `view.zoomEnabled`, `view.panEnabled`, and `node.draggable` all to `false`.

```ts
const configs = defineConfigs({
  view: {
    panEnabled: false,
    zoomEnabled: false,
  },
  node: {
    draggable: false,
  },
})
```

I hope this helps you.
Best Regards,

**Comment by dash14** [comment]
I close this issue for now.
If you have any other question, please reopen this issue.
