### ISSUE TITLE
Use a function on the panEnabled property

### ISSUE THREAD

**Issue by Coeurdecedre** [dash14/v-network-graph#66]
Hi ! I would like to know if there was a way to use a function on the panEnabled property that return a boolean ? I tried but it doesn't work.

![image](https://user-images.githubusercontent.com/93530235/173359351-65a4fcf0-f5cd-47db-828f-680f17532e60.png)

Thanks for your reply ! :)

**Comment by dash14** [comment]
Hi @Coeurdecedre,
Unfortunately, specifying a function to `panEnabled` is not supported at this time.
I guess the following steps can be used as an alternative, so please try them out.
(The following explanation assumes the Composition API, but if a different syntax is used, please read it accordingly.)

* Wrap configs in `reactive()` and then pass it to `v-network-graph`.
  ```ts
  const configs = reactive(
    defineConfigs({
      view: {
        panEnabled: false,
        // ...
      },
      // ...
    })
  )
  ```
  ```vue
  <v-network-graph ... :configs="configs" />
  ```
* Observe `$store.state.keyboard.holdingShift` changes by `watch` and assign to `configs.view.panEnabled` when the value is changed
  ```ts
  watch(() => /* store value */, value => {
    configs.view.panEnabled = value
  })
  ```

I hope this helps you.

**Comment by Coeurdecedre** [comment]
Thanks @dash14  , I'll use watchers then ! However, would it be possible for you to add the possibility of adding a function this this property in the near future ? Thanks again ^^

**Comment by dash14** [comment]
Hi @Coeurdecedre,
Thank you for your reply.
I realized that by using JavaScript's getter functionality, it seems to be possible to achieve your requirement.
Please check the below example:
- https://dash14.github.io/v-network-graph/examples/misc.html#specify-function-in-view-config

In some cases, node and edge configs require a function to be specified as a config in order to retrieve values from each object. However, since `configs.view.*` has a single value and the above alternatives are available, it's not currently considering extending the view configs.

Best Regards,

**Comment by dash14** [comment]
Hi @Coeurdecedre,
Thanks for trying it out!
I think `this` in the getter does not point to a component and `this.holdingShift` is `undefined`.
It may work to create a function that binds `this` outside of the getter and call it inside the getter, as shown below.

```js
  data() {
    const panEnabled = () => !this.holdingShift;
    return {
      vNGConfigs: {
        view: {
          get panEnabled() {
            return panEnabled();
          },
```
Best Regards,

**Comment by Coeurdecedre** [comment]
Hi @dash14 ! Thank you very much for your help !

I put the configs as a computed and it's working !  :)

Best Regards !

**Comment by dash14** [comment]
Hi @Coeurdecedre,
Thank you for your reply. I'm glad you got it resolved! 👍 
Best Regards!
