### ISSUE TITLE
Different force configuration for different types of nodes

### ISSUE THREAD

**Issue by markus-ebner** [dash14/v-network-graph#7]
Is it possible to have a different force configuration for different nodes/edges?

**Comment by dash14** [comment]
Unfortunately, this is not possible with only the features provided by v-network-graph.
However, it may be possible to achieve this by doing the following:
* Implement a custom `LayoutHandler` ([code](https://github.com/dash14/v-network-graph/blob/e85006d518abc7f3988d271edb7a3222c1ec9b80/src/layouts/handler.ts#L18-L21)) using d3-force with multiple configuration.
  * The existing `ForceLayout` ([code](https://github.com/dash14/v-network-graph/blob/df11426f2cd9bd096820f5102f2f7046cf075eb0/src/layouts/force.ts#L31)) class can be used as a reference in the implementation.
* Specify the instance of this new developed `LayoutHandler` to the `view.layoutHandler` config.

The `view.layoutHandler` config is specified as follows:
```ts
const configs = reactive({
  view: {
    layoutHandler: YourOwnLayoutHandler()
  },
  // ...
})
```

```html
<v-network-graph
  :nodes="nodes"
  :edges="edges"
  :configs="configs"
/>
```

**Comment by markus-ebner** [comment]
Okay, I may need this feature in the future. 
Thanks for the information about the self written LayoutHandlers, I wasn't aware of this.
At least I can develop it myself, if it isn't available at the time.  ;)
