### ISSUE TITLE
Which release can support Vue 2?

### ISSUE THREAD

**Issue by dylanzx** [dash14/v-network-graph#84]
As the title said.

**Comment by Suniron** [comment]
> As the title said.

As it say in documentation, only vue 3 is supported.

Also, vue 2 is not supported after end of next year, I suppose that's it's not realing interesting to do pains to adapt code for vue 2 🤷‍♂️

**Comment by dash14** [comment]
Hi @dylanzx,
As @Suniron replied, v-network-graph is only supported in Vue 3.
There are no future plans to support Vue 2.
