### ISSUE TITLE
Add label zOrder configuration

### ISSUE THREAD

**Issue by lucagrammer** [dash14/v-network-graph#87]
Hi, thanks for this great and very useful library. 
I would like to suggest a very small improvement that would greatly improve the usability, which is often compromised when using paths. Indeed, paths are the last element rendered on the SVG and therefore they cover the labels associated with the nodes, making them unreadable. 

My suggestion is to change the rendering order or provide a zOrder option in configs to change it. In fact there is no other way (css z-index doesn't work with SVGs) to alter this property.

<img width="193" alt="Schermata 2022-09-12 alle 13 31 20" src="https://user-images.githubusercontent.com/50906588/189642886-26b50df8-06d3-4b8a-93df-3b4fbc632779.png">

Thank you very much!

**Comment by dash14** [comment]
Hi @lucagrammer,
Thank you for suggesting a nice feature!
Sorry for the delay, but I have implemented and released this feature. ([v0.8.1](https://github.com/dash14/v-network-graph/releases/tag/v0.8.1))
Targets not only labels but also built-in layers such as nodes and focus rings, allowing the order of layers to be changed.
For more details, please refer to the example.
https://dash14.github.io/v-network-graph/examples/layers.html#change-the-order-of-built-in-layers

Thank you very much for your support!

**Comment by lucagrammer** [comment]
Thank you very much for your work
