### ISSUE TITLE
add collapse featutre

### ISSUE THREAD

**Issue by drAliRahnema** [dash14/v-network-graph#93]
hi
thank you a lot for your best graph tool
i want to collapses some child nodes and when click parent node show hidden ones

**Comment by dash14** [comment]
Hi @drAliRahnema,
Thank you for your feedback and feature request!
Although not an extension of v-network-graph, I have created an example that provides simple node expand and collapse.
https://dash14.github.io/v-network-graph/examples/misc.html#node-expand-collapse

As mentioned in the example, at this time there is no plan to develop this feature as a priority, for keeping generally and simplicity in this library.
In the future, I may incorporate code equivalent to the example into the library to make it more usable, but this is not planned, at least not in the immediate future, so please check the example if you need it.

Best Regards

**Comment by drAliRahnema** [comment]
thank you very much
