### ISSUE TITLE
export as svg bug report

### ISSUE THREAD

**Issue by drAliRahnema** [dash14/v-network-graph#94]
hi @dash14 
when export graph that has image as node background, the image will not be appeared in the result
for example:
![image](https://user-images.githubusercontent.com/16861558/201514053-862d5f7e-032a-4980-831a-d71310593e90.png)
thank you

**Comment by dash14** [comment]
Hi @drAliRahnema,
Thank you for reporting issue!
The export feature was getting the SVG as is, and also the <image/> tag was not changed. If the image was specified as a relative URL, it would be invalid after download.
As a new feature in [v0.7.0](https://github.com/dash14/v-network-graph/releases/tag/v0.7.0), I have added the feature to convert image URLs to data-uri(base64) and retrieve them.
Also I created an [example](https://dash14.github.io/v-network-graph/examples/misc.html#get-the-content-as-svg-data), so please try it out.

**Comment by drAliRahnema** [comment]
you are amazing man, thank you a lot
