### ISSUE TITLE
Vue version 3.2.43 bug

### ISSUE THREAD

**Issue by vshepel16** [dash14/v-network-graph#98]
First render
Expected undefined, got empty array

Uncaught (in promise) TypeError: c.has is not a function

<img width="988" alt="Screenshot 2022-12-12 at 13 26 07" src="https://user-images.githubusercontent.com/23277509/207033924-5038b0c9-9761-4d72-9748-746a35a6bcb9.png">

**Comment by vshepel16** [comment]
![image](https://user-images.githubusercontent.com/23277509/207077715-a853e902-1738-4a45-b15d-d8066e0bbeb0.png)

**Comment by dash14** [comment]
Hi @vshepel16,
Thank you for the report!
Since the cause of this error is a bug in Vue, which has already been fixed, I do not consider it necessary to address this issue in v-network-graph.
Please specify the Vue version of 3.2.44 or later in the package.json file.
I appreciate your support!
